// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcmqtsndvydvhtvdrftz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjbXF0c25kdnlkdmh0dmRyZnR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NzUwNDYsImV4cCI6MjA3MDE1MTA0Nn0.rWbdXQC0BO5ghPzeMNm4THeZ9ZmNyVfyUAkFE1_Pbb4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});